// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.ElevenLabs.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\convai\conversation\get-signed-url
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetSignedUrlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetSignedUrlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/convai/conversation/get-signed-url?agent_id={agent_id}{&branch_id*,environment*,include_conversation_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetSignedUrlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/convai/conversation/get-signed-url?agent_id={agent_id}{&branch_id*,environment*,include_conversation_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a signed url to start a conversation with an agent with an agent that requires authorization
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ConversationSignedUrlResponseModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConversationSignedUrlResponseModel?> GetAsync(Action<RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder.GetSignedUrlRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConversationSignedUrlResponseModel> GetAsync(Action<RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder.GetSignedUrlRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.ElevenLabs.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConversationSignedUrlResponseModel>(requestInfo, global::Soenneker.ElevenLabs.OpenApiClient.Models.ConversationSignedUrlResponseModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a signed url to start a conversation with an agent with an agent that requires authorization
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder.GetSignedUrlRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder.GetSignedUrlRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a signed url to start a conversation with an agent with an agent that requires authorization
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetSignedUrlRequestBuilderGetQueryParameters 
        {
            /// <summary>The id of the agent you&apos;re taking the action on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("agent_id")]
            public string? AgentId { get; set; }
#nullable restore
#else
            [QueryParameter("agent_id")]
            public string AgentId { get; set; }
#endif
            /// <summary>The ID of the branch to use</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("branch_id")]
            public string? BranchId { get; set; }
#nullable restore
#else
            [QueryParameter("branch_id")]
            public string BranchId { get; set; }
#endif
            /// <summary>The environment to use for resolving environment variables (e.g. &apos;production&apos;, &apos;staging&apos;). Defaults to &apos;production&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("environment")]
            public string? Environment { get; set; }
#nullable restore
#else
            [QueryParameter("environment")]
            public string Environment { get; set; }
#endif
            /// <summary>Whether to include a conversation_id with the response. If included, the conversation_signature cannot be used again.</summary>
            [QueryParameter("include_conversation_id")]
            public bool? IncludeConversationId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetSignedUrlRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversation.GetSignedUrl.GetSignedUrlRequestBuilder.GetSignedUrlRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
