// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages.SmartSearch;
using Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages.TextSearch;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\convai\conversations\messages
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The smartSearch property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages.SmartSearch.SmartSearchRequestBuilder SmartSearch
        {
            get => new global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages.SmartSearch.SmartSearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The textSearch property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages.TextSearch.TextSearchRequestBuilder TextSearch
        {
            get => new global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages.TextSearch.TextSearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages.MessagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/convai/conversations/messages", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.Conversations.Messages.MessagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/convai/conversations/messages", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
