// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AllowedOutputFormats
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "mp3_22050_32")]
        #pragma warning disable CS1591
        Mp3_22050_32,
        #pragma warning restore CS1591
        [EnumMember(Value = "mp3_24000_48")]
        #pragma warning disable CS1591
        Mp3_24000_48,
        #pragma warning restore CS1591
        [EnumMember(Value = "mp3_44100_32")]
        #pragma warning disable CS1591
        Mp3_44100_32,
        #pragma warning restore CS1591
        [EnumMember(Value = "mp3_44100_64")]
        #pragma warning disable CS1591
        Mp3_44100_64,
        #pragma warning restore CS1591
        [EnumMember(Value = "mp3_44100_96")]
        #pragma warning disable CS1591
        Mp3_44100_96,
        #pragma warning restore CS1591
        [EnumMember(Value = "mp3_44100_128")]
        #pragma warning disable CS1591
        Mp3_44100_128,
        #pragma warning restore CS1591
        [EnumMember(Value = "mp3_44100_192")]
        #pragma warning disable CS1591
        Mp3_44100_192,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_8000")]
        #pragma warning disable CS1591
        Pcm_8000,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_16000")]
        #pragma warning disable CS1591
        Pcm_16000,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_22050")]
        #pragma warning disable CS1591
        Pcm_22050,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_24000")]
        #pragma warning disable CS1591
        Pcm_24000,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_32000")]
        #pragma warning disable CS1591
        Pcm_32000,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_44100")]
        #pragma warning disable CS1591
        Pcm_44100,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm_48000")]
        #pragma warning disable CS1591
        Pcm_48000,
        #pragma warning restore CS1591
        [EnumMember(Value = "ulaw_8000")]
        #pragma warning disable CS1591
        Ulaw_8000,
        #pragma warning restore CS1591
        [EnumMember(Value = "alaw_8000")]
        #pragma warning disable CS1591
        Alaw_8000,
        #pragma warning restore CS1591
        [EnumMember(Value = "opus_48000_32")]
        #pragma warning disable CS1591
        Opus_48000_32,
        #pragma warning restore CS1591
        [EnumMember(Value = "opus_48000_64")]
        #pragma warning disable CS1591
        Opus_48000_64,
        #pragma warning restore CS1591
        [EnumMember(Value = "opus_48000_96")]
        #pragma warning disable CS1591
        Opus_48000_96,
        #pragma warning restore CS1591
        [EnumMember(Value = "opus_48000_128")]
        #pragma warning disable CS1591
        Opus_48000_128,
        #pragma warning restore CS1591
        [EnumMember(Value = "opus_48000_192")]
        #pragma warning disable CS1591
        Opus_48000_192,
        #pragma warning restore CS1591
    }
}
