// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>Identifiers for audio voice filters.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AudioFilterId
    {
        [EnumMember(Value = "phone")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
        [EnumMember(Value = "low_quality_phone")]
        #pragma warning disable CS1591
        LowQualityPhone,
        #pragma warning restore CS1591
        [EnumMember(Value = "bright_phone")]
        #pragma warning disable CS1591
        BrightPhone,
        #pragma warning restore CS1591
    }
}
