// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AudioIsolationHistoryItemResponseModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at_unix property</summary>
        public int? CreatedAtUnix { get; set; }
        /// <summary>The download_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadUrl { get; set; }
#nullable restore
#else
        public string DownloadUrl { get; set; }
#endif
        /// <summary>The duration_seconds property</summary>
        public double? DurationSeconds { get; set; }
        /// <summary>The format property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>The icon_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IconUrl { get; set; }
#nullable restore
#else
        public string IconUrl { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The preview_b64 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewB64 { get; set; }
#nullable restore
#else
        public string PreviewB64 { get; set; }
#endif
        /// <summary>The processing property</summary>
        public bool? Processing { get; set; }
        /// <summary>The source_video_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceVideoUrl { get; set; }
#nullable restore
#else
        public string SourceVideoUrl { get; set; }
#endif
        /// <summary>The supports_video property</summary>
        public bool? SupportsVideo { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The video_processing_failed property</summary>
        public bool? VideoProcessingFailed { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioIsolationHistoryItemResponseModel"/> and sets the default values.
        /// </summary>
        public AudioIsolationHistoryItemResponseModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioIsolationHistoryItemResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioIsolationHistoryItemResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioIsolationHistoryItemResponseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at_unix", n => { CreatedAtUnix = n.GetIntValue(); } },
                { "download_url", n => { DownloadUrl = n.GetStringValue(); } },
                { "duration_seconds", n => { DurationSeconds = n.GetDoubleValue(); } },
                { "format", n => { Format = n.GetStringValue(); } },
                { "icon_url", n => { IconUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "preview_b64", n => { PreviewB64 = n.GetStringValue(); } },
                { "processing", n => { Processing = n.GetBoolValue(); } },
                { "source_video_url", n => { SourceVideoUrl = n.GetStringValue(); } },
                { "supports_video", n => { SupportsVideo = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "video_processing_failed", n => { VideoProcessingFailed = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("created_at_unix", CreatedAtUnix);
            writer.WriteStringValue("download_url", DownloadUrl);
            writer.WriteDoubleValue("duration_seconds", DurationSeconds);
            writer.WriteStringValue("format", Format);
            writer.WriteStringValue("icon_url", IconUrl);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("preview_b64", PreviewB64);
            writer.WriteBoolValue("processing", Processing);
            writer.WriteStringValue("source_video_url", SourceVideoUrl);
            writer.WriteBoolValue("supports_video", SupportsVideo);
            writer.WriteStringValue("title", Title);
            writer.WriteBoolValue("video_processing_failed", VideoProcessingFailed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
