// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The id of the stem variation to use.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BodyStemSeparationV1MusicStemSeparationPostStemVariationId
    {
        [EnumMember(Value = "two_stems_v1")]
        #pragma warning disable CS1591
        TwoStemsV1,
        #pragma warning restore CS1591
        [EnumMember(Value = "six_stems_v1")]
        #pragma warning disable CS1591
        SixStemsV1,
        #pragma warning restore CS1591
    }
}
