// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentId { get; set; }
#nullable restore
#else
        public string AgentId { get; set; }
#endif
        /// <summary>The agent_phone_number_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_agent_phone_number_id? AgentPhoneNumberId { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_agent_phone_number_id AgentPhoneNumberId { get; set; }
#endif
        /// <summary>The branch_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_branch_id? BranchId { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_branch_id BranchId { get; set; }
#endif
        /// <summary>The call_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallName { get; set; }
#nullable restore
#else
        public string CallName { get; set; }
#endif
        /// <summary>The environment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_environment? Environment { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_environment Environment { get; set; }
#endif
        /// <summary>The recipients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundCallRecipient>? Recipients { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundCallRecipient> Recipients { get; set; }
#endif
        /// <summary>The scheduled_time_unix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_scheduled_time_unix? ScheduledTimeUnix { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_scheduled_time_unix ScheduledTimeUnix { get; set; }
#endif
        /// <summary>Maximum number of simultaneous calls for this batch. When set, dispatch is governed by this limit rather than workspace/agent capacity percentages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_target_concurrency_limit? TargetConcurrencyLimit { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_target_concurrency_limit TargetConcurrencyLimit { get; set; }
#endif
        /// <summary>The telephony_call_config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.TelephonyCallConfig? TelephonyCallConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.TelephonyCallConfig TelephonyCallConfig { get; set; }
#endif
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_timezone? Timezone { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_timezone Timezone { get; set; }
#endif
        /// <summary>The whatsapp_params property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_whatsapp_params? WhatsappParams { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_whatsapp_params WhatsappParams { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post"/> and sets the default values.
        /// </summary>
        public Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_id", n => { AgentId = n.GetStringValue(); } },
                { "agent_phone_number_id", n => { AgentPhoneNumberId = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_agent_phone_number_id>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_agent_phone_number_id.CreateFromDiscriminatorValue); } },
                { "branch_id", n => { BranchId = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_branch_id>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_branch_id.CreateFromDiscriminatorValue); } },
                { "call_name", n => { CallName = n.GetStringValue(); } },
                { "environment", n => { Environment = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_environment>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_environment.CreateFromDiscriminatorValue); } },
                { "recipients", n => { Recipients = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundCallRecipient>(global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundCallRecipient.CreateFromDiscriminatorValue)?.AsList(); } },
                { "scheduled_time_unix", n => { ScheduledTimeUnix = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_scheduled_time_unix>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_scheduled_time_unix.CreateFromDiscriminatorValue); } },
                { "target_concurrency_limit", n => { TargetConcurrencyLimit = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_target_concurrency_limit>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_target_concurrency_limit.CreateFromDiscriminatorValue); } },
                { "telephony_call_config", n => { TelephonyCallConfig = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TelephonyCallConfig>(global::Soenneker.ElevenLabs.OpenApiClient.Models.TelephonyCallConfig.CreateFromDiscriminatorValue); } },
                { "timezone", n => { Timezone = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_timezone>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_timezone.CreateFromDiscriminatorValue); } },
                { "whatsapp_params", n => { WhatsappParams = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_whatsapp_params>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_whatsapp_params.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("agent_id", AgentId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_agent_phone_number_id>("agent_phone_number_id", AgentPhoneNumberId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_branch_id>("branch_id", BranchId);
            writer.WriteStringValue("call_name", CallName);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_environment>("environment", Environment);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundCallRecipient>("recipients", Recipients);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_scheduled_time_unix>("scheduled_time_unix", ScheduledTimeUnix);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_target_concurrency_limit>("target_concurrency_limit", TargetConcurrencyLimit);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TelephonyCallConfig>("telephony_call_config", TelephonyCallConfig);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_timezone>("timezone", Timezone);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Body_Submit_a_batch_call_request__v1_convai_batch_calling_submit_post_whatsapp_params>("whatsapp_params", WhatsappParams);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
