// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The model to use for the generation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BytedanceSeedream5LiteRequest_model_id
    {
        [EnumMember(Value = "bytedance-seedream-5-lite")]
        #pragma warning disable CS1591
        BytedanceSeedream5Lite,
        #pragma warning restore CS1591
    }
}
