// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>
    /// Request body for the ByteDance Seedream 5.0 Pro image model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BytedanceSeedream5ProRequest : IParsable
    {
        /// <summary>The aspect ratio of the output image. With `auto`, the model picks an aspect ratio based on the inputs.</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequestAspectRatio? AspectRatio { get; set; }
        /// <summary>Up to 10 reference images to edit or draw from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageReference>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageReference> Images { get; set; }
#endif
        /// <summary>The model to use for the generation.</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequest_model_id? ModelId { get; set; }
        /// <summary>A text description of the image to generate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>The resolution of the output image.</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequestResolution? Resolution { get; set; }
        /// <summary>&quot;A seed for reproducible generation: the same seed and inputs give similar output across generations. Omit for random.&quot;</summary>
        public int? Seed { get; set; }
        /// <summary>Include to send the generation&apos;s result to the workspace&apos;s configured flows webhooks once it completes or fails. The webhook payload matches the terminal response of the corresponding GET endpoint.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookTarget? Webhook { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookTarget Webhook { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aspect_ratio", n => { AspectRatio = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequestAspectRatio>(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageReference>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageReference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "model_id", n => { ModelId = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequest_model_id>(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "resolution", n => { Resolution = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequestResolution>(); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "webhook", n => { Webhook = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookTarget>(global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookTarget.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequestAspectRatio>("aspect_ratio", AspectRatio);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageReference>("images", Images);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequest_model_id>("model_id", ModelId);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.BytedanceSeedream5ProRequestResolution>("resolution", Resolution);
            writer.WriteIntValue("seed", Seed);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookTarget>("webhook", Webhook);
        }
    }
}
#pragma warning restore CS0618
