// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The type of tool</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CodeToolConfigOutput_type
    {
        [EnumMember(Value = "code")]
        #pragma warning disable CS1591
        Code,
        #pragma warning restore CS1591
    }
}
