// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConvAiStoredSecretDependencies : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agents property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesAgentsItem>? Agents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesAgentsItem> Agents { get; set; }
#endif
        /// <summary>Whether there are more agent dependents beyond the returned preview</summary>
        public bool? AgentsHasMore { get; set; }
        /// <summary>The mcp_servers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesMcpServersItem>? McpServers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesMcpServersItem> McpServers { get; set; }
#endif
        /// <summary>The others property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.SecretDependencyType?>? Others { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.SecretDependencyType?> Others { get; set; }
#endif
        /// <summary>The phone_numbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.DependentPhoneNumberIdentifier>? PhoneNumbers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.DependentPhoneNumberIdentifier> PhoneNumbers { get; set; }
#endif
        /// <summary>Whether there are more phone number dependents beyond the returned preview</summary>
        public bool? PhoneNumbersHasMore { get; set; }
        /// <summary>The tools property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesToolsItem>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesToolsItem> Tools { get; set; }
#endif
        /// <summary>Whether there are more tool dependents beyond the returned preview</summary>
        public bool? ToolsHasMore { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependencies"/> and sets the default values.
        /// </summary>
        public ConvAiStoredSecretDependencies()
        {
            AdditionalData = new Dictionary<string, object>();
            AgentsHasMore = false;
            PhoneNumbersHasMore = false;
            ToolsHasMore = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependencies"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependencies CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependencies();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agents", n => { Agents = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesAgentsItem>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesAgentsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "agents_has_more", n => { AgentsHasMore = n.GetBoolValue(); } },
                { "mcp_servers", n => { McpServers = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesMcpServersItem>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesMcpServersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "others", n => { Others = n.GetCollectionOfEnumValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.SecretDependencyType>()?.AsList(); } },
                { "phone_numbers", n => { PhoneNumbers = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.DependentPhoneNumberIdentifier>(global::Soenneker.ElevenLabs.OpenApiClient.Models.DependentPhoneNumberIdentifier.CreateFromDiscriminatorValue)?.AsList(); } },
                { "phone_numbers_has_more", n => { PhoneNumbersHasMore = n.GetBoolValue(); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesToolsItem>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesToolsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tools_has_more", n => { ToolsHasMore = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesAgentsItem>("agents", Agents);
            writer.WriteBoolValue("agents_has_more", AgentsHasMore);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesMcpServersItem>("mcp_servers", McpServers);
            writer.WriteCollectionOfEnumValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.SecretDependencyType>("others", Others);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.DependentPhoneNumberIdentifier>("phone_numbers", PhoneNumbers);
            writer.WriteBoolValue("phone_numbers_has_more", PhoneNumbersHasMore);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ConvAiStoredSecretDependenciesToolsItem>("tools", Tools);
            writer.WriteBoolValue("tools_has_more", ToolsHasMore);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
