// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateSimulationTestRequest_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "simulation")]
        #pragma warning disable CS1591
        Simulation,
        #pragma warning restore CS1591
    }
}
