// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateOAuth2JWTRequest_auth_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "oauth2_jwt")]
        #pragma warning disable CS1591
        Oauth2_jwt,
        #pragma warning restore CS1591
    }
}
