// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateTransferRuleParams : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to offer the post_dial_digits parameter, set from the receptionists&apos; enable_play_keypad_touch_tone_tool config. Digits saved while that is off are dropped when the receptionist is built, so the parameter is hidden rather than accepted and ignored.</summary>
        public bool? PostDialDigitsEnabled { get; set; }
        /// <summary>The smb_tool_type property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.CreateTransferRuleParams_smb_tool_type? SmbToolType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.CreateTransferRuleParams"/> and sets the default values.
        /// </summary>
        public CreateTransferRuleParams()
        {
            AdditionalData = new Dictionary<string, object>();
            PostDialDigitsEnabled = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.CreateTransferRuleParams"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.CreateTransferRuleParams CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.CreateTransferRuleParams();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "post_dial_digits_enabled", n => { PostDialDigitsEnabled = n.GetBoolValue(); } },
                { "smb_tool_type", n => { SmbToolType = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.CreateTransferRuleParams_smb_tool_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("post_dial_digits_enabled", PostDialDigitsEnabled);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.CreateTransferRuleParams_smb_tool_type>("smb_tool_type", SmbToolType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
