// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmbeddingModelEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "e5_mistral_7b_instruct")]
        #pragma warning disable CS1591
        E5_mistral_7b_instruct,
        #pragma warning restore CS1591
        [EnumMember(Value = "multilingual_e5_large_instruct")]
        #pragma warning disable CS1591
        Multilingual_e5_large_instruct,
        #pragma warning restore CS1591
    }
}
