// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The background of the output image. With `auto`, the model picks the background that suits the image.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GptImage1RequestBackground
    {
        [EnumMember(Value = "transparent")]
        #pragma warning disable CS1591
        Transparent,
        #pragma warning restore CS1591
        [EnumMember(Value = "opaque")]
        #pragma warning disable CS1591
        Opaque,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
    }
}
