// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ImageReferencePromptPart_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "image_reference")]
        #pragma warning disable CS1591
        Image_reference,
        #pragma warning restore CS1591
    }
}
