// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class KlingOmniVideoParameters : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aspect_ratio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio? AspectRatio { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio AspectRatio { get; set; }
#endif
        /// <summary>The duration_secs property</summary>
        public int? DurationSecs { get; set; }
        /// <summary>The elements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.VideoElement>? Elements { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.VideoElement> Elements { get; set; }
#endif
        /// <summary>The end_frame property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage? EndFrame { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage EndFrame { get; set; }
#endif
        /// <summary>The keep_audio property</summary>
        public bool? KeepAudio { get; set; }
        /// <summary>The reference_images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>? ReferenceImages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage> ReferenceImages { get; set; }
#endif
        /// <summary>The start_frame property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage? StartFrame { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage StartFrame { get; set; }
#endif
        /// <summary>The video property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceVideo? Video { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceVideo Video { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.KlingOmniVideoParameters"/> and sets the default values.
        /// </summary>
        public KlingOmniVideoParameters()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.KlingOmniVideoParameters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.KlingOmniVideoParameters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.KlingOmniVideoParameters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aspect_ratio", n => { AspectRatio = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio.CreateFromDiscriminatorValue); } },
                { "duration_secs", n => { DurationSecs = n.GetIntValue(); } },
                { "elements", n => { Elements = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.VideoElement>(global::Soenneker.ElevenLabs.OpenApiClient.Models.VideoElement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "end_frame", n => { EndFrame = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage.CreateFromDiscriminatorValue); } },
                { "keep_audio", n => { KeepAudio = n.GetBoolValue(); } },
                { "reference_images", n => { ReferenceImages = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_frame", n => { StartFrame = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage.CreateFromDiscriminatorValue); } },
                { "video", n => { Video = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceVideo>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceVideo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio>("aspect_ratio", AspectRatio);
            writer.WriteIntValue("duration_secs", DurationSecs);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.VideoElement>("elements", Elements);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>("end_frame", EndFrame);
            writer.WriteBoolValue("keep_audio", KeepAudio);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>("reference_images", ReferenceImages);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>("start_frame", StartFrame);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceVideo>("video", Video);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
