// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LibraryVoiceResponseModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accent of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Accent { get; set; }
#nullable restore
#else
        public string Accent { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The age of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Age { get; set; }
#nullable restore
#else
        public string Age { get; set; }
#endif
        /// <summary>The category of the voice.</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModel_category? Category { get; set; }
        /// <summary>The number of times the voice has been cloned.</summary>
        public int? ClonedByCount { get; set; }
        /// <summary>The date the voice was added to the library in Unix time.</summary>
        public int? DateUnix { get; set; }
        /// <summary>The description of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelDescription? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelDescription Description { get; set; }
#endif
        /// <summary>The descriptive of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Descriptive { get; set; }
#nullable restore
#else
        public string Descriptive { get; set; }
#endif
        /// <summary>Whether the voice is featured.</summary>
        public bool? Featured { get; set; }
        /// <summary>The rate of the voice in USD per 1000 credits. null if default</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelFiatRate? FiatRate { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelFiatRate FiatRate { get; set; }
#endif
        /// <summary>Whether free users are allowed to use the voice.</summary>
        public bool? FreeUsersAllowed { get; set; }
        /// <summary>The gender of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gender { get; set; }
#nullable restore
#else
        public string Gender { get; set; }
#endif
        /// <summary>The image URL of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelImageUrl? ImageUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelImageUrl ImageUrl { get; set; }
#endif
        /// <summary>The Instagram username of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelInstagramUsername? InstagramUsername { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelInstagramUsername InstagramUsername { get; set; }
#endif
        /// <summary>Whether the voice was added by the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsAddedByUser? IsAddedByUser { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsAddedByUser IsAddedByUser { get; set; }
#endif
        /// <summary>Whether the voice is bookmarked by the current user. Only relevant when is_added_by_user is True.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsBookmarked? IsBookmarked { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsBookmarked IsBookmarked { get; set; }
#endif
        /// <summary>The language of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLanguage? Language { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLanguage Language { get; set; }
#endif
        /// <summary>Whether live moderation is enabled for the voice.</summary>
        public bool? LiveModerationEnabled { get; set; }
        /// <summary>The locale of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLocale? Locale { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLocale Locale { get; set; }
#endif
        /// <summary>The name of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The notice period of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelNoticePeriod? NoticePeriod { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelNoticePeriod NoticePeriod { get; set; }
#endif
        /// <summary>The play API usage character count of the voice in the last year.</summary>
        public int? PlayApiUsageCharacterCount1y { get; set; }
        /// <summary>The preview URL of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelPreviewUrl? PreviewUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelPreviewUrl PreviewUrl { get; set; }
#endif
        /// <summary>The public owner id of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicOwnerId { get; set; }
#nullable restore
#else
        public string PublicOwnerId { get; set; }
#endif
        /// <summary>The rate multiplier of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelRate? Rate { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelRate Rate { get; set; }
#endif
        /// <summary>The TikTok username of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTiktokUsername? TiktokUsername { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTiktokUsername TiktokUsername { get; set; }
#endif
        /// <summary>The Twitter username of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTwitterUsername? TwitterUsername { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTwitterUsername TwitterUsername { get; set; }
#endif
        /// <summary>The usage character count of the voice in the last year.</summary>
        public int? UsageCharacterCount1y { get; set; }
        /// <summary>The usage character count of the voice in the last 7 days.</summary>
        public int? UsageCharacterCount7d { get; set; }
        /// <summary>The use case of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UseCase { get; set; }
#nullable restore
#else
        public string UseCase { get; set; }
#endif
        /// <summary>The verified languages of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelVerifiedLanguages? VerifiedLanguages { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelVerifiedLanguages VerifiedLanguages { get; set; }
#endif
        /// <summary>The id of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceId { get; set; }
#nullable restore
#else
        public string VoiceId { get; set; }
#endif
        /// <summary>The YouTube username of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelYoutubeUsername? YoutubeUsername { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelYoutubeUsername YoutubeUsername { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModel"/> and sets the default values.
        /// </summary>
        public LibraryVoiceResponseModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accent", n => { Accent = n.GetStringValue(); } },
                { "age", n => { Age = n.GetStringValue(); } },
                { "category", n => { Category = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModel_category>(); } },
                { "cloned_by_count", n => { ClonedByCount = n.GetIntValue(); } },
                { "date_unix", n => { DateUnix = n.GetIntValue(); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelDescription>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelDescription.CreateFromDiscriminatorValue); } },
                { "descriptive", n => { Descriptive = n.GetStringValue(); } },
                { "featured", n => { Featured = n.GetBoolValue(); } },
                { "fiat_rate", n => { FiatRate = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelFiatRate>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelFiatRate.CreateFromDiscriminatorValue); } },
                { "free_users_allowed", n => { FreeUsersAllowed = n.GetBoolValue(); } },
                { "gender", n => { Gender = n.GetStringValue(); } },
                { "image_url", n => { ImageUrl = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelImageUrl>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelImageUrl.CreateFromDiscriminatorValue); } },
                { "instagram_username", n => { InstagramUsername = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelInstagramUsername>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelInstagramUsername.CreateFromDiscriminatorValue); } },
                { "is_added_by_user", n => { IsAddedByUser = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsAddedByUser>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsAddedByUser.CreateFromDiscriminatorValue); } },
                { "is_bookmarked", n => { IsBookmarked = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsBookmarked>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsBookmarked.CreateFromDiscriminatorValue); } },
                { "language", n => { Language = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLanguage>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLanguage.CreateFromDiscriminatorValue); } },
                { "live_moderation_enabled", n => { LiveModerationEnabled = n.GetBoolValue(); } },
                { "locale", n => { Locale = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLocale>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLocale.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notice_period", n => { NoticePeriod = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelNoticePeriod>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelNoticePeriod.CreateFromDiscriminatorValue); } },
                { "play_api_usage_character_count_1y", n => { PlayApiUsageCharacterCount1y = n.GetIntValue(); } },
                { "preview_url", n => { PreviewUrl = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelPreviewUrl>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelPreviewUrl.CreateFromDiscriminatorValue); } },
                { "public_owner_id", n => { PublicOwnerId = n.GetStringValue(); } },
                { "rate", n => { Rate = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelRate>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelRate.CreateFromDiscriminatorValue); } },
                { "tiktok_username", n => { TiktokUsername = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTiktokUsername>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTiktokUsername.CreateFromDiscriminatorValue); } },
                { "twitter_username", n => { TwitterUsername = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTwitterUsername>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTwitterUsername.CreateFromDiscriminatorValue); } },
                { "usage_character_count_1y", n => { UsageCharacterCount1y = n.GetIntValue(); } },
                { "usage_character_count_7d", n => { UsageCharacterCount7d = n.GetIntValue(); } },
                { "use_case", n => { UseCase = n.GetStringValue(); } },
                { "verified_languages", n => { VerifiedLanguages = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelVerifiedLanguages>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelVerifiedLanguages.CreateFromDiscriminatorValue); } },
                { "voice_id", n => { VoiceId = n.GetStringValue(); } },
                { "youtube_username", n => { YoutubeUsername = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelYoutubeUsername>(global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelYoutubeUsername.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accent", Accent);
            writer.WriteStringValue("age", Age);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModel_category>("category", Category);
            writer.WriteIntValue("cloned_by_count", ClonedByCount);
            writer.WriteIntValue("date_unix", DateUnix);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelDescription>("description", Description);
            writer.WriteStringValue("descriptive", Descriptive);
            writer.WriteBoolValue("featured", Featured);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelFiatRate>("fiat_rate", FiatRate);
            writer.WriteBoolValue("free_users_allowed", FreeUsersAllowed);
            writer.WriteStringValue("gender", Gender);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelImageUrl>("image_url", ImageUrl);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelInstagramUsername>("instagram_username", InstagramUsername);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsAddedByUser>("is_added_by_user", IsAddedByUser);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelIsBookmarked>("is_bookmarked", IsBookmarked);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLanguage>("language", Language);
            writer.WriteBoolValue("live_moderation_enabled", LiveModerationEnabled);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelLocale>("locale", Locale);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelNoticePeriod>("notice_period", NoticePeriod);
            writer.WriteIntValue("play_api_usage_character_count_1y", PlayApiUsageCharacterCount1y);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelPreviewUrl>("preview_url", PreviewUrl);
            writer.WriteStringValue("public_owner_id", PublicOwnerId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelRate>("rate", Rate);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTiktokUsername>("tiktok_username", TiktokUsername);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelTwitterUsername>("twitter_username", TwitterUsername);
            writer.WriteIntValue("usage_character_count_1y", UsageCharacterCount1y);
            writer.WriteIntValue("usage_character_count_7d", UsageCharacterCount7d);
            writer.WriteStringValue("use_case", UseCase);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelVerifiedLanguages>("verified_languages", VerifiedLanguages);
            writer.WriteStringValue("voice_id", VoiceId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.LibraryVoiceResponseModelYoutubeUsername>("youtube_username", YoutubeUsername);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
