// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListTransferRulesParams_smb_tool_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "list_transfer_rules")]
        #pragma warning disable CS1591
        ListTransferRules,
        #pragma warning restore CS1591
    }
}
