// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LockReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "trial_ended")]
        #pragma warning disable CS1591
        TrialEnded,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription_downgrade")]
        #pragma warning disable CS1591
        SubscriptionDowngrade,
        #pragma warning restore CS1591
        [EnumMember(Value = "exposed_publicly")]
        #pragma warning disable CS1591
        ExposedPublicly,
        #pragma warning restore CS1591
        [EnumMember(Value = "self_disabled")]
        #pragma warning disable CS1591
        SelfDisabled,
        #pragma warning restore CS1591
    }
}
