// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>Defines the MCP server-level approval policy for tool execution.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum McpApprovalPolicy
    {
        [EnumMember(Value = "auto_approve_all")]
        #pragma warning disable CS1591
        AutoApproveAll,
        #pragma warning restore CS1591
        [EnumMember(Value = "require_approval_all")]
        #pragma warning disable CS1591
        RequireApprovalAll,
        #pragma warning restore CS1591
        [EnumMember(Value = "require_approval_per_tool")]
        #pragma warning disable CS1591
        RequireApprovalPerTool,
        #pragma warning restore CS1591
    }
}
