// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MediaCodec
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "G722/8000")]
        #pragma warning disable CS1591
        G7228000,
        #pragma warning restore CS1591
        [EnumMember(Value = "PCMU/8000")]
        #pragma warning disable CS1591
        Pcmu8000,
        #pragma warning restore CS1591
        [EnumMember(Value = "PCMA/8000")]
        #pragma warning disable CS1591
        Pcma8000,
        #pragma warning restore CS1591
    }
}
