// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The tier to change to.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PendingSubscriptionSwitchResponseModelNextTier
    {
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "starter")]
        #pragma warning disable CS1591
        Starter,
        #pragma warning restore CS1591
        [EnumMember(Value = "creator")]
        #pragma warning disable CS1591
        Creator,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro")]
        #pragma warning disable CS1591
        Pro,
        #pragma warning restore CS1591
        [EnumMember(Value = "growing_business")]
        #pragma warning disable CS1591
        GrowingBusiness,
        #pragma warning restore CS1591
        [EnumMember(Value = "scale_2024_08_10")]
        #pragma warning disable CS1591
        Scale20240810,
        #pragma warning restore CS1591
        [EnumMember(Value = "grant_tier_1_2025_07_23")]
        #pragma warning disable CS1591
        GrantTier120250723,
        #pragma warning restore CS1591
        [EnumMember(Value = "grant_tier_2_2025_07_23")]
        #pragma warning disable CS1591
        GrantTier220250723,
        #pragma warning restore CS1591
        [EnumMember(Value = "trial")]
        #pragma warning disable CS1591
        Trial,
        #pragma warning restore CS1591
        [EnumMember(Value = "enterprise")]
        #pragma warning disable CS1591
        Enterprise,
        #pragma warning restore CS1591
    }
}
