// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The type of podcast to create.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PodcastConversationMode_type
    {
        [EnumMember(Value = "conversation")]
        #pragma warning disable CS1591
        Conversation,
        #pragma warning restore CS1591
    }
}
