// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The state of the project.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectExtendedResponseModel_state
    {
        [EnumMember(Value = "creating")]
        #pragma warning disable CS1591
        Creating,
        #pragma warning restore CS1591
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
        [EnumMember(Value = "converting")]
        #pragma warning disable CS1591
        Converting,
        #pragma warning restore CS1591
        [EnumMember(Value = "in_queue")]
        #pragma warning disable CS1591
        In_queue,
        #pragma warning restore CS1591
    }
}
