// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProjectExtendedResponseModel_caption_style_text_style_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
        [EnumMember(Value = "italic")]
        #pragma warning disable CS1591
        Italic,
        #pragma warning restore CS1591
    }
}
