// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ApiIntegrationWebhookToolConfigInput"/>, <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ClientToolConfigInput"/>, <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.McpToolConfigInput"/>, <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.SmbToolConfig"/>, <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.SystemToolConfigInput"/>, <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookToolConfigInput"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PromptAgentApiModelInputToolsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ApiIntegrationWebhookToolConfigInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ApiIntegrationWebhookToolConfigInput? ApiIntegrationWebhookToolConfigInput { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ApiIntegrationWebhookToolConfigInput ApiIntegrationWebhookToolConfigInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ClientToolConfigInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ClientToolConfigInput? ClientToolConfigInput { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ClientToolConfigInput ClientToolConfigInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.McpToolConfigInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.McpToolConfigInput? McpToolConfigInput { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.McpToolConfigInput McpToolConfigInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.SmbToolConfig"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SmbToolConfig? SmbToolConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SmbToolConfig SmbToolConfig { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.SystemToolConfigInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SystemToolConfigInput? SystemToolConfigInput { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SystemToolConfigInput SystemToolConfigInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookToolConfigInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookToolConfigInput? WebhookToolConfigInput { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookToolConfigInput WebhookToolConfigInput { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.PromptAgentApiModelInputToolsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.PromptAgentApiModelInputToolsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.ElevenLabs.OpenApiClient.Models.PromptAgentApiModelInputToolsItem();
            if("ApiIntegrationWebhookToolConfigInput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApiIntegrationWebhookToolConfigInput = new global::Soenneker.ElevenLabs.OpenApiClient.Models.ApiIntegrationWebhookToolConfigInput();
            }
            else if("client".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ClientToolConfigInput = new global::Soenneker.ElevenLabs.OpenApiClient.Models.ClientToolConfigInput();
            }
            else if("mcp".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.McpToolConfigInput = new global::Soenneker.ElevenLabs.OpenApiClient.Models.McpToolConfigInput();
            }
            else if("smb".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SmbToolConfig = new global::Soenneker.ElevenLabs.OpenApiClient.Models.SmbToolConfig();
            }
            else if("system".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SystemToolConfigInput = new global::Soenneker.ElevenLabs.OpenApiClient.Models.SystemToolConfigInput();
            }
            else if("webhook".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WebhookToolConfigInput = new global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookToolConfigInput();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ApiIntegrationWebhookToolConfigInput != null)
            {
                return ApiIntegrationWebhookToolConfigInput.GetFieldDeserializers();
            }
            else if(ClientToolConfigInput != null)
            {
                return ClientToolConfigInput.GetFieldDeserializers();
            }
            else if(McpToolConfigInput != null)
            {
                return McpToolConfigInput.GetFieldDeserializers();
            }
            else if(SmbToolConfig != null)
            {
                return SmbToolConfig.GetFieldDeserializers();
            }
            else if(SystemToolConfigInput != null)
            {
                return SystemToolConfigInput.GetFieldDeserializers();
            }
            else if(WebhookToolConfigInput != null)
            {
                return WebhookToolConfigInput.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ApiIntegrationWebhookToolConfigInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ApiIntegrationWebhookToolConfigInput>(null, ApiIntegrationWebhookToolConfigInput);
            }
            else if(ClientToolConfigInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ClientToolConfigInput>(null, ClientToolConfigInput);
            }
            else if(McpToolConfigInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.McpToolConfigInput>(null, McpToolConfigInput);
            }
            else if(SmbToolConfig != null)
            {
                writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SmbToolConfig>(null, SmbToolConfig);
            }
            else if(SystemToolConfigInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SystemToolConfigInput>(null, SystemToolConfigInput);
            }
            else if(WebhookToolConfigInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookToolConfigInput>(null, WebhookToolConfigInput);
            }
        }
    }
}
#pragma warning restore CS0618
