// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResourceMetadataResponseModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The access level for anonymous users. If None, the resource is not shared publicly.</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel_anonymous_access_level_override? AnonymousAccessLevelOverride { get; set; }
        /// <summary>The ID of the user who created the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorUserId { get; set; }
#nullable restore
#else
        public string CreatorUserId { get; set; }
#endif
        /// <summary>The ID of the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceId { get; set; }
#nullable restore
#else
        public string ResourceId { get; set; }
#endif
        /// <summary>The name of the resource, if available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceName { get; set; }
#nullable restore
#else
        public string ResourceName { get; set; }
#endif
        /// <summary>Resource types that can be shared in the workspace. The name always need to match the collection names</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WorkspaceResourceType? ResourceType { get; set; }
        /// <summary>A mapping of roles to group IDs. When the resource is shared with a user, the group id is the user&apos;s id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel_role_to_group_ids? RoleToGroupIds { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel_role_to_group_ids RoleToGroupIds { get; set; }
#endif
        /// <summary>List of options for sharing the resource further in the workspace. These are users who don&apos;t have access to the resource yet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ShareOptionResponseModel>? ShareOptions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.ShareOptionResponseModel> ShareOptions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel"/> and sets the default values.
        /// </summary>
        public ResourceMetadataResponseModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "anonymous_access_level_override", n => { AnonymousAccessLevelOverride = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel_anonymous_access_level_override>(); } },
                { "creator_user_id", n => { CreatorUserId = n.GetStringValue(); } },
                { "resource_id", n => { ResourceId = n.GetStringValue(); } },
                { "resource_name", n => { ResourceName = n.GetStringValue(); } },
                { "resource_type", n => { ResourceType = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WorkspaceResourceType>(); } },
                { "role_to_group_ids", n => { RoleToGroupIds = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel_role_to_group_ids>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel_role_to_group_ids.CreateFromDiscriminatorValue); } },
                { "share_options", n => { ShareOptions = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ShareOptionResponseModel>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ShareOptionResponseModel.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel_anonymous_access_level_override>("anonymous_access_level_override", AnonymousAccessLevelOverride);
            writer.WriteStringValue("creator_user_id", CreatorUserId);
            writer.WriteStringValue("resource_id", ResourceId);
            writer.WriteStringValue("resource_name", ResourceName);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WorkspaceResourceType>("resource_type", ResourceType);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ResourceMetadataResponseModel_role_to_group_ids>("role_to_group_ids", RoleToGroupIds);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.ShareOptionResponseModel>("share_options", ShareOptions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
