// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RunAgentTestsRequestModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Configuration overrides to use for testing. If not provided, the agent&apos;s default configuration will be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_agent_config_override? AgentConfigOverride { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_agent_config_override AgentConfigOverride { get; set; }
#endif
        /// <summary>ID of the branch to run the tests on. If not provided, the tests will be run on the agent default configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_branch_id? BranchId { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_branch_id BranchId { get; set; }
#endif
        /// <summary>List of tests to run on the agent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.SingleTestRunRequestModel>? Tests { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.SingleTestRunRequestModel> Tests { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel"/> and sets the default values.
        /// </summary>
        public RunAgentTestsRequestModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_config_override", n => { AgentConfigOverride = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_agent_config_override>(global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_agent_config_override.CreateFromDiscriminatorValue); } },
                { "branch_id", n => { BranchId = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_branch_id>(global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_branch_id.CreateFromDiscriminatorValue); } },
                { "tests", n => { Tests = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.SingleTestRunRequestModel>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SingleTestRunRequestModel.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_agent_config_override>("agent_config_override", AgentConfigOverride);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.RunAgentTestsRequestModel_branch_id>("branch_id", BranchId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.SingleTestRunRequestModel>("tests", Tests);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
