// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SIPLogMessageDirection
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "in")]
        #pragma warning disable CS1591
        In,
        #pragma warning restore CS1591
        [EnumMember(Value = "out")]
        #pragma warning disable CS1591
        Out,
        #pragma warning restore CS1591
    }
}
