// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SIPMediaEncryptionEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "allowed")]
        #pragma warning disable CS1591
        Allowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "required")]
        #pragma warning disable CS1591
        Required,
        #pragma warning restore CS1591
    }
}
