// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SpeechHistoryItemResponseModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alignments of the history item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAlignments? Alignments { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAlignments Alignments { get; set; }
#endif
        /// <summary>Avatar context if this generation was created from the Avatars video editor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAvatarContext? AvatarContext { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAvatarContext AvatarContext { get; set; }
#endif
        /// <summary>The character count change from.</summary>
        public int? CharacterCountChangeFrom { get; set; }
        /// <summary>The character count change to.</summary>
        public int? CharacterCountChangeTo { get; set; }
        /// <summary>The content type of the generated item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>Unix timestamp of when the item was created.</summary>
        public int? DateUnix { get; set; }
        /// <summary>The dialogue (voice and text pairs) used to generate the audio item. If this is set then the top level `text` and `voice_id` fields will be empty.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelDialogue? Dialogue { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelDialogue Dialogue { get; set; }
#endif
        /// <summary>Feedback associated with the generated item. Returns null if no feedback has been provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelFeedback? Feedback { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelFeedback Feedback { get; set; }
#endif
        /// <summary>The ID of the history item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HistoryItemId { get; set; }
#nullable restore
#else
        public string HistoryItemId { get; set; }
#endif
        /// <summary>The ID of the model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelModelId? ModelId { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelModelId ModelId { get; set; }
#endif
        /// <summary>The output format the audio was originally generated in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelOutputFormat? OutputFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelOutputFormat OutputFormat { get; set; }
#endif
        /// <summary>The ID of the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelRequestId? RequestId { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelRequestId RequestId { get; set; }
#endif
        /// <summary>The settings of the history item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSettings? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSettings Settings { get; set; }
#endif
        /// <summary>The ID of the share link.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelShareLinkId? ShareLinkId { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelShareLinkId ShareLinkId { get; set; }
#endif
        /// <summary>The source of the history item. Either TTS (text to speech), STS (speech to text), AN (audio native), Projects, Dubbing, PlayAPI, PD (pronunciation dictionary) or ConvAI (Agents Platform).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSource? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSource Source { get; set; }
#endif
        /// <summary>The state of the history item.</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModel_state? State { get; set; }
        /// <summary>The text used to generate the audio item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelText? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelText Text { get; set; }
#endif
        /// <summary>The category of the voice. Either &apos;premade&apos;, &apos;cloned&apos;, &apos;generated&apos; or &apos;professional&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceCategory? VoiceCategory { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceCategory VoiceCategory { get; set; }
#endif
        /// <summary>The ID of the voice used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceId? VoiceId { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceId VoiceId { get; set; }
#endif
        /// <summary>The name of the voice.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceName? VoiceName { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceName VoiceName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModel"/> and sets the default values.
        /// </summary>
        public SpeechHistoryItemResponseModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alignments", n => { Alignments = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAlignments>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAlignments.CreateFromDiscriminatorValue); } },
                { "avatar_context", n => { AvatarContext = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAvatarContext>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAvatarContext.CreateFromDiscriminatorValue); } },
                { "character_count_change_from", n => { CharacterCountChangeFrom = n.GetIntValue(); } },
                { "character_count_change_to", n => { CharacterCountChangeTo = n.GetIntValue(); } },
                { "content_type", n => { ContentType = n.GetStringValue(); } },
                { "date_unix", n => { DateUnix = n.GetIntValue(); } },
                { "dialogue", n => { Dialogue = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelDialogue>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelDialogue.CreateFromDiscriminatorValue); } },
                { "feedback", n => { Feedback = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelFeedback>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelFeedback.CreateFromDiscriminatorValue); } },
                { "history_item_id", n => { HistoryItemId = n.GetStringValue(); } },
                { "model_id", n => { ModelId = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelModelId>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelModelId.CreateFromDiscriminatorValue); } },
                { "output_format", n => { OutputFormat = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelOutputFormat>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelOutputFormat.CreateFromDiscriminatorValue); } },
                { "request_id", n => { RequestId = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelRequestId>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelRequestId.CreateFromDiscriminatorValue); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSettings>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSettings.CreateFromDiscriminatorValue); } },
                { "share_link_id", n => { ShareLinkId = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelShareLinkId>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelShareLinkId.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSource>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSource.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModel_state>(); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelText>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelText.CreateFromDiscriminatorValue); } },
                { "voice_category", n => { VoiceCategory = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceCategory>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceCategory.CreateFromDiscriminatorValue); } },
                { "voice_id", n => { VoiceId = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceId>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceId.CreateFromDiscriminatorValue); } },
                { "voice_name", n => { VoiceName = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceName>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceName.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAlignments>("alignments", Alignments);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelAvatarContext>("avatar_context", AvatarContext);
            writer.WriteIntValue("character_count_change_from", CharacterCountChangeFrom);
            writer.WriteIntValue("character_count_change_to", CharacterCountChangeTo);
            writer.WriteStringValue("content_type", ContentType);
            writer.WriteIntValue("date_unix", DateUnix);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelDialogue>("dialogue", Dialogue);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelFeedback>("feedback", Feedback);
            writer.WriteStringValue("history_item_id", HistoryItemId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelModelId>("model_id", ModelId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelOutputFormat>("output_format", OutputFormat);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelRequestId>("request_id", RequestId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSettings>("settings", Settings);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelShareLinkId>("share_link_id", ShareLinkId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelSource>("source", Source);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModel_state>("state", State);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelText>("text", Text);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceCategory>("voice_category", VoiceCategory);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceId>("voice_id", VoiceId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SpeechHistoryItemResponseModelVoiceName>("voice_name", VoiceName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
