// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The category of the voice. Either &apos;premade&apos;, &apos;cloned&apos;, &apos;generated&apos; or &apos;professional&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SpeechHistoryItemResponseModel_voice_category
    {
        [EnumMember(Value = "premade")]
        #pragma warning disable CS1591
        Premade,
        #pragma warning restore CS1591
        [EnumMember(Value = "cloned")]
        #pragma warning disable CS1591
        Cloned,
        #pragma warning restore CS1591
        [EnumMember(Value = "generated")]
        #pragma warning disable CS1591
        Generated,
        #pragma warning restore CS1591
        [EnumMember(Value = "professional")]
        #pragma warning disable CS1591
        Professional,
        #pragma warning restore CS1591
    }
}
