// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubtitleOrderItemRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cue_options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.CueOptionsRequest? CueOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.CueOptionsRequest CueOptions { get; set; }
#endif
        /// <summary>List of target language codes. Subtitles will be generated for each media file in each destination language.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DestinationLanguages { get; set; }
#nullable restore
#else
        public List<string> DestinationLanguages { get; set; }
#endif
        /// <summary>Optional free-text instructions for the subtitling team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>The type of order item.</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SubtitleOrderItemRequest_kind? Kind { get; set; }
        /// <summary>The IDs of the uploaded media files to generate subtitles for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MediaIds { get; set; }
#nullable restore
#else
        public List<string> MediaIds { get; set; }
#endif
        /// <summary>Whether subtitles should use SDH format, which includes descriptions for deaf and hard-of-hearing viewers.</summary>
        public bool? Sdh { get; set; }
        /// <summary>The language code of the source media (e.g. &apos;en&apos;, &apos;es&apos;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceLanguage { get; set; }
#nullable restore
#else
        public string SourceLanguage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.SubtitleOrderItemRequest"/> and sets the default values.
        /// </summary>
        public SubtitleOrderItemRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Kind = global::Soenneker.ElevenLabs.OpenApiClient.Models.SubtitleOrderItemRequest_kind.Subtitles;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.SubtitleOrderItemRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.SubtitleOrderItemRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.SubtitleOrderItemRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cue_options", n => { CueOptions = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.CueOptionsRequest>(global::Soenneker.ElevenLabs.OpenApiClient.Models.CueOptionsRequest.CreateFromDiscriminatorValue); } },
                { "destination_languages", n => { DestinationLanguages = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SubtitleOrderItemRequest_kind>(); } },
                { "media_ids", n => { MediaIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sdh", n => { Sdh = n.GetBoolValue(); } },
                { "source_language", n => { SourceLanguage = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.CueOptionsRequest>("cue_options", CueOptions);
            writer.WriteCollectionOfPrimitiveValues<string>("destination_languages", DestinationLanguages);
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SubtitleOrderItemRequest_kind>("kind", Kind);
            writer.WriteCollectionOfPrimitiveValues<string>("media_ids", MediaIds);
            writer.WriteBoolValue("sdh", Sdh);
            writer.WriteStringValue("source_language", SourceLanguage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
