// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TranscriptionOrderItemRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional free-text instructions for the transcription team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>The type of order item.</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.TranscriptionOrderItemRequest_kind? Kind { get; set; }
        /// <summary>The IDs of the uploaded media files to transcribe.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MediaIds { get; set; }
#nullable restore
#else
        public List<string> MediaIds { get; set; }
#endif
        /// <summary>The language code of the source media (e.g. &apos;en&apos;, &apos;es&apos;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceLanguage { get; set; }
#nullable restore
#else
        public string SourceLanguage { get; set; }
#endif
        /// <summary>Whether to transcribe every word exactly, including filler words.</summary>
        public bool? Verbatim { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.TranscriptionOrderItemRequest"/> and sets the default values.
        /// </summary>
        public TranscriptionOrderItemRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Verbatim = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.TranscriptionOrderItemRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.TranscriptionOrderItemRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.TranscriptionOrderItemRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TranscriptionOrderItemRequest_kind>(); } },
                { "media_ids", n => { MediaIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "source_language", n => { SourceLanguage = n.GetStringValue(); } },
                { "verbatim", n => { Verbatim = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TranscriptionOrderItemRequest_kind>("kind", Kind);
            writer.WriteCollectionOfPrimitiveValues<string>("media_ids", MediaIds);
            writer.WriteStringValue("source_language", SourceLanguage);
            writer.WriteBoolValue("verbatim", Verbatim);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
