// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TtsConversationalConfigInput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agent_output_audio_format property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsOutputFormat? AgentOutputAudioFormat { get; set; }
        /// <summary>An optional filter applied to the audio output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioFilterIdWrapper? AudioFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioFilterIdWrapper AudioFilter { get; set; }
#endif
        /// <summary>Opt-in to SSML phoneme tag handling for V3 models. When enabled, phoneme tags (inline and from pronunciation dictionaries) are parsed into inline IPA before being sent to the model.</summary>
        public bool? EnablePhonemeTags { get; set; }
        /// <summary>When enabled, applies expressive audio tags prompt. Automatically disabled for non-v3 models.</summary>
        public bool? ExpressiveMode { get; set; }
        /// <summary>The model_id property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsConversationalModel? ModelId { get; set; }
        /// <summary>The optimize_streaming_latency property</summary>
        public int? OptimizeStreamingLatency { get; set; }
        /// <summary>The pronunciation dictionary locators</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.PydanticPronunciationDictionaryVersionLocator>? PronunciationDictionaryLocators { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.PydanticPronunciationDictionaryVersionLocator> PronunciationDictionaryLocators { get; set; }
#endif
        /// <summary>The similarity boost for generated speech</summary>
        public double? SimilarityBoost { get; set; }
        /// <summary>The speed of generated speech</summary>
        public double? Speed { get; set; }
        /// <summary>The stability of generated speech</summary>
        public double? Stability { get; set; }
        /// <summary>Suggested audio tags to boost expressive speech (for eleven_v3 and eleven_v3_conversational models). The agent can still use other tags not listed here.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.SuggestedAudioTag>? SuggestedAudioTags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.SuggestedAudioTag> SuggestedAudioTags { get; set; }
#endif
        /// <summary>Additional supported voices for the agent</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.SupportedVoice>? SupportedVoices { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.SupportedVoice> SupportedVoices { get; set; }
#endif
        /// <summary>Method for converting numbers to words before sending to TTS</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.TextNormalisationType? TextNormalisationType { get; set; }
        /// <summary>The voice ID to use for TTS</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceId { get; set; }
#nullable restore
#else
        public string VoiceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsConversationalConfigInput"/> and sets the default values.
        /// </summary>
        public TtsConversationalConfigInput()
        {
            AdditionalData = new Dictionary<string, object>();
            EnablePhonemeTags = true;
            ExpressiveMode = true;
            SimilarityBoost = 0.8;
            Speed = 1.0;
            Stability = 0.5;
            VoiceId = "cjVigY5qzO86Huf0OWal";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsConversationalConfigInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsConversationalConfigInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsConversationalConfigInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_output_audio_format", n => { AgentOutputAudioFormat = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsOutputFormat>(); } },
                { "audio_filter", n => { AudioFilter = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioFilterIdWrapper>(global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioFilterIdWrapper.CreateFromDiscriminatorValue); } },
                { "enable_phoneme_tags", n => { EnablePhonemeTags = n.GetBoolValue(); } },
                { "expressive_mode", n => { ExpressiveMode = n.GetBoolValue(); } },
                { "model_id", n => { ModelId = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsConversationalModel>(); } },
                { "optimize_streaming_latency", n => { OptimizeStreamingLatency = n.GetIntValue(); } },
                { "pronunciation_dictionary_locators", n => { PronunciationDictionaryLocators = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.PydanticPronunciationDictionaryVersionLocator>(global::Soenneker.ElevenLabs.OpenApiClient.Models.PydanticPronunciationDictionaryVersionLocator.CreateFromDiscriminatorValue)?.AsList(); } },
                { "similarity_boost", n => { SimilarityBoost = n.GetDoubleValue(); } },
                { "speed", n => { Speed = n.GetDoubleValue(); } },
                { "stability", n => { Stability = n.GetDoubleValue(); } },
                { "suggested_audio_tags", n => { SuggestedAudioTags = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.SuggestedAudioTag>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SuggestedAudioTag.CreateFromDiscriminatorValue)?.AsList(); } },
                { "supported_voices", n => { SupportedVoices = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.SupportedVoice>(global::Soenneker.ElevenLabs.OpenApiClient.Models.SupportedVoice.CreateFromDiscriminatorValue)?.AsList(); } },
                { "text_normalisation_type", n => { TextNormalisationType = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TextNormalisationType>(); } },
                { "voice_id", n => { VoiceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsOutputFormat>("agent_output_audio_format", AgentOutputAudioFormat);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.AudioFilterIdWrapper>("audio_filter", AudioFilter);
            writer.WriteBoolValue("enable_phoneme_tags", EnablePhonemeTags);
            writer.WriteBoolValue("expressive_mode", ExpressiveMode);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TtsConversationalModel>("model_id", ModelId);
            writer.WriteIntValue("optimize_streaming_latency", OptimizeStreamingLatency);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.PydanticPronunciationDictionaryVersionLocator>("pronunciation_dictionary_locators", PronunciationDictionaryLocators);
            writer.WriteDoubleValue("similarity_boost", SimilarityBoost);
            writer.WriteDoubleValue("speed", Speed);
            writer.WriteDoubleValue("stability", Stability);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.SuggestedAudioTag>("suggested_audio_tags", SuggestedAudioTags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.SupportedVoice>("supported_voices", SupportedVoices);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.TextNormalisationType>("text_normalisation_type", TextNormalisationType);
            writer.WriteStringValue("voice_id", VoiceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
