// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdatePhoneNumberRequestOutboundTrunkConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Hostname or IP the SIP INVITE is sent to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>Map of dynamic variable name to header name for attributes_to_headers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelAttributesToHeadersProperty? AttributesToHeaders { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelAttributesToHeadersProperty AttributesToHeaders { get; set; }
#endif
        /// <summary>Optional digest authentication credentials (username/password). If not provided, ACL authentication is assumed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelCredentials? Credentials { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelCredentials Credentials { get; set; }
#endif
        /// <summary>Media codecs that should be offered in the SDP for outbound calls. If empty, all supported codecs are offered.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.MediaCodec?>? EnabledCodecs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.MediaCodec?> EnabledCodecs { get; set; }
#endif
        /// <summary>SIP X-* headers for INVITE request. These headers are sent as-is and may help identify this call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelHeadersProperty? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelHeadersProperty Headers { get; set; }
#endif
        /// <summary>The media_encryption property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SipMediaEncryptionEnum? MediaEncryption { get; set; }
        /// <summary>The transport property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.SipTrunkTransportEnum? Transport { get; set; }
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.UpdatePhoneNumberRequestOutboundTrunkConfig"/> and sets the default values.
        /// </summary>
        public UpdatePhoneNumberRequestOutboundTrunkConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.UpdatePhoneNumberRequestOutboundTrunkConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.UpdatePhoneNumberRequestOutboundTrunkConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.UpdatePhoneNumberRequestOutboundTrunkConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "attributes_to_headers", n => { AttributesToHeaders = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelAttributesToHeadersProperty>(global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelAttributesToHeadersProperty.CreateFromDiscriminatorValue); } },
                { "credentials", n => { Credentials = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelCredentials>(global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelCredentials.CreateFromDiscriminatorValue); } },
                { "enabled_codecs", n => { EnabledCodecs = n.GetCollectionOfEnumValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.MediaCodec>()?.AsList(); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelHeadersProperty>(global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelHeadersProperty.CreateFromDiscriminatorValue); } },
                { "media_encryption", n => { MediaEncryption = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SipMediaEncryptionEnum>(); } },
                { "transport", n => { Transport = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SipTrunkTransportEnum>(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelAttributesToHeadersProperty>("attributes_to_headers", AttributesToHeaders);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelCredentials>("credentials", Credentials);
            writer.WriteCollectionOfEnumValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.MediaCodec>("enabled_codecs", EnabledCodecs);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.OutboundSipTrunkConfigRequestModelHeadersProperty>("headers", Headers);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SipMediaEncryptionEnum>("media_encryption", MediaEncryption);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.SipTrunkTransportEnum>("transport", Transport);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
