// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    /// <summary>The review status of the voice.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VoiceSharingResponseModelReviewStatus
    {
        [EnumMember(Value = "not_requested")]
        #pragma warning disable CS1591
        NotRequested,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "declined")]
        #pragma warning disable CS1591
        Declined,
        #pragma warning restore CS1591
        [EnumMember(Value = "allowed")]
        #pragma warning disable CS1591
        Allowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "allowed_with_changes")]
        #pragma warning disable CS1591
        AllowedWithChanges,
        #pragma warning restore CS1591
    }
}
