// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Wan25PreviewVideoParameters : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aspect_ratio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio? AspectRatio { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio AspectRatio { get; set; }
#endif
        /// <summary>The audio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceAudio? Audio { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceAudio Audio { get; set; }
#endif
        /// <summary>The duration_secs property</summary>
        public int? DurationSecs { get; set; }
        /// <summary>The enhance_prompt property</summary>
        public bool? EnhancePrompt { get; set; }
        /// <summary>The negative_prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters.Wan25PreviewVideoParameters_negative_prompt? NegativePrompt { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters.Wan25PreviewVideoParameters_negative_prompt NegativePrompt { get; set; }
#endif
        /// <summary>The resolution property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters_resolution? Resolution { get; set; }
        /// <summary>The seed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Seed? Seed { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Seed Seed { get; set; }
#endif
        /// <summary>The start_frame property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage? StartFrame { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage StartFrame { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters"/> and sets the default values.
        /// </summary>
        public Wan25PreviewVideoParameters()
        {
            AdditionalData = new Dictionary<string, object>();
            Resolution = global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters_resolution.SevenTwoZerop;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aspect_ratio", n => { AspectRatio = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio.CreateFromDiscriminatorValue); } },
                { "audio", n => { Audio = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceAudio>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceAudio.CreateFromDiscriminatorValue); } },
                { "duration_secs", n => { DurationSecs = n.GetIntValue(); } },
                { "enhance_prompt", n => { EnhancePrompt = n.GetBoolValue(); } },
                { "negative_prompt", n => { NegativePrompt = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters.Wan25PreviewVideoParameters_negative_prompt>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters.Wan25PreviewVideoParameters_negative_prompt.CreateFromDiscriminatorValue); } },
                { "resolution", n => { Resolution = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters_resolution>(); } },
                { "seed", n => { Seed = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Seed>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Seed.CreateFromDiscriminatorValue); } },
                { "start_frame", n => { StartFrame = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>(global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Aspect_Ratio>("aspect_ratio", AspectRatio);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceAudio>("audio", Audio);
            writer.WriteIntValue("duration_secs", DurationSecs);
            writer.WriteBoolValue("enhance_prompt", EnhancePrompt);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters.Wan25PreviewVideoParameters_negative_prompt>("negative_prompt", NegativePrompt);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters_resolution>("resolution", Resolution);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Seed>("seed", Seed);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceImage>("start_frame", StartFrame);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.Negative_Prompt"/>, <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceText"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Wan25PreviewVideoParameters_negative_prompt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.Negative_Prompt"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.Negative_Prompt? NegativePrompt { get; set; }
#nullable restore
#else
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.Negative_Prompt NegativePrompt { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceText"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceText? ReferenceText { get; set; }
#nullable restore
#else
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceText ReferenceText { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters.Wan25PreviewVideoParameters_negative_prompt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters.Wan25PreviewVideoParameters_negative_prompt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.ElevenLabs.OpenApiClient.Models.Wan25PreviewVideoParameters.Wan25PreviewVideoParameters_negative_prompt();
                result.NegativePrompt = new global::Soenneker.ElevenLabs.OpenApiClient.Models.Negative_Prompt();
                result.ReferenceText = new global::Soenneker.ElevenLabs.OpenApiClient.Models.ReferenceText();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NegativePrompt != null || ReferenceText != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NegativePrompt, ReferenceText);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Negative_Prompt>(null, NegativePrompt, ReferenceText);
            }
        }
    }
}
#pragma warning restore CS0618
