// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WhatsAppAuthResponse_provider
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "whatsapp")]
        #pragma warning disable CS1591
        Whatsapp,
        #pragma warning restore CS1591
    }
}
