// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WidgetConfig_Input : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action text of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Action_Text? ActionText { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Action_Text ActionText { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the widget should always be expanded</summary>
        public bool? AlwaysExpanded { get; set; }
        /// <summary>The avatar of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input.WidgetConfig_Input_avatar? Avatar { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input.WidgetConfig_Input_avatar Avatar { get; set; }
#endif
        /// <summary>The background color of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BgColor { get; set; }
#nullable restore
#else
        public string BgColor { get; set; }
#endif
        /// <summary>The border color of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BorderColor { get; set; }
#nullable restore
#else
        public string BorderColor { get; set; }
#endif
        /// <summary>The border radius of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Border_Radius? BorderRadius { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Border_Radius BorderRadius { get; set; }
#endif
        /// <summary>The button color of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BtnColor { get; set; }
#nullable restore
#else
        public string BtnColor { get; set; }
#endif
        /// <summary>The button radius of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Btn_Radius? BtnRadius { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Btn_Radius BtnRadius { get; set; }
#endif
        /// <summary>The button text color of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BtnTextColor { get; set; }
#nullable restore
#else
        public string BtnTextColor { get; set; }
#endif
        /// <summary>Whether to enable the conversation mode toggle in the widget</summary>
        public bool? ConversationModeToggleEnabled { get; set; }
        /// <summary>The custom avatar path</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Custom_Avatar_Path? CustomAvatarPath { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Custom_Avatar_Path CustomAvatarPath { get; set; }
#endif
        /// <summary>Whether the widget should be expanded by default</summary>
        public bool? DefaultExpanded { get; set; }
        /// <summary>Whether to disable the banner</summary>
        public bool? DisableBanner { get; set; }
        /// <summary>Whether the widget can be dismissed by the user</summary>
        public bool? Dismissible { get; set; }
        /// <summary>The end call text of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.End_Call_Text? EndCallText { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.End_Call_Text EndCallText { get; set; }
#endif
        /// <summary>Configuration for feedback collected at the end of the conversation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetEndFeedbackConfig? EndFeedback { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetEndFeedbackConfig EndFeedback { get; set; }
#endif
        /// <summary>The expandable property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetExpandable? Expandable { get; set; }
        /// <summary>The expand text of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Expand_Text? ExpandText { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Expand_Text ExpandText { get; set; }
#endif
        /// <summary>The feedback_mode property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetFeedbackMode? FeedbackMode { get; set; }
        /// <summary>The focus color of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FocusColor { get; set; }
#nullable restore
#else
        public string FocusColor { get; set; }
#endif
        /// <summary>Language presets for the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input_language_presets? LanguagePresets { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input_language_presets LanguagePresets { get; set; }
#endif
        /// <summary>Whether to show the language selector</summary>
        public bool? LanguageSelector { get; set; }
        /// <summary>The text to display when the agent is listening</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Listening_Text? ListeningText { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Listening_Text ListeningText { get; set; }
#endif
        /// <summary>&quot;List of allowed hostnames for clickable markdown links. Use { hostname: &apos;*&apos; } to allow any domain. Empty means no links are allowed.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.AllowlistItem>? MarkdownLinkAllowedHosts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ElevenLabs.OpenApiClient.Models.AllowlistItem> MarkdownLinkAllowedHosts { get; set; }
#endif
        /// <summary>Whether to allow http:// in addition to https:// for allowed hosts</summary>
        public bool? MarkdownLinkAllowHttp { get; set; }
        /// <summary>Whether to automatically include www. variants of allowed hosts</summary>
        public bool? MarkdownLinkIncludeWww { get; set; }
        /// <summary>Whether to enable mic muting</summary>
        public bool? MicMutingEnabled { get; set; }
        /// <summary>The override link for the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Override_Link? OverrideLink { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Override_Link OverrideLink { get; set; }
#endif
        /// <summary>The placement property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetPlacement? Placement { get; set; }
        /// <summary>Whether to show terms and conditions on the shareable page</summary>
        public bool? ShareablePageShowTerms { get; set; }
        /// <summary>The text to display when sharing</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Shareable_Page_Text? ShareablePageText { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Shareable_Page_Text ShareablePageText { get; set; }
#endif
        /// <summary>Whether to show agent working/done/error status during tool use</summary>
        public bool? ShowAgentStatus { get; set; }
        /// <summary>Whether to show the avatar when the widget is collapsed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Show_Avatar_When_Collapsed? ShowAvatarWhenCollapsed { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Show_Avatar_When_Collapsed ShowAvatarWhenCollapsed { get; set; }
#endif
        /// <summary>Whether to show the conversation ID after disconnection.</summary>
        public bool? ShowConversationId { get; set; }
        /// <summary>The text to display when the agent is speaking</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Speaking_Text? SpeakingText { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Speaking_Text SpeakingText { get; set; }
#endif
        /// <summary>The start call text of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Start_Call_Text? StartCallText { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Start_Call_Text StartCallText { get; set; }
#endif
        /// <summary>Whether to strip audio markup from messages.</summary>
        public bool? StripAudioTags { get; set; }
        /// <summary>The styles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetStyles? Styles { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetStyles Styles { get; set; }
#endif
        /// <summary>Whether the widget can switch to text only mode</summary>
        public bool? SupportsTextOnly { get; set; }
        /// <summary>Theme for code block syntax highlighting. Defaults to auto-detection by the widget when not set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Syntax_Highlight_Theme? SyntaxHighlightTheme { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Syntax_Highlight_Theme SyntaxHighlightTheme { get; set; }
#endif
        /// <summary>The HTML to display for terms and conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Html? TermsHtml { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Html TermsHtml { get; set; }
#endif
        /// <summary>The key to display for terms and conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Key? TermsKey { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Key TermsKey { get; set; }
#endif
        /// <summary>The text to display for terms and conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Text? TermsText { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Text TermsText { get; set; }
#endif
        /// <summary>The text color of the widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextColor { get; set; }
#nullable restore
#else
        public string TextColor { get; set; }
#endif
        /// <summary>The text_contents property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetTextContents? TextContents { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetTextContents TextContents { get; set; }
#endif
        /// <summary>Whether the user should be able to send text messages</summary>
        public bool? TextInputEnabled { get; set; }
        /// <summary>Whether the widget should show the conversation transcript as it goes on</summary>
        public bool? TranscriptEnabled { get; set; }
        /// <summary>The variant property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.EmbedVariant? Variant { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input"/> and sets the default values.
        /// </summary>
        public WidgetConfig_Input()
        {
            AdditionalData = new Dictionary<string, object>();
            BgColor = "#ffffff";
            BorderColor = "#e1e1e1";
            BtnColor = "#000000";
            BtnTextColor = "#ffffff";
            Expandable = global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetExpandable.Never;
            FeedbackMode = global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetFeedbackMode.None;
            FocusColor = "#000000";
            Placement = global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetPlacement.BottomRight;
            TextColor = "#000000";
            Variant = global::Soenneker.ElevenLabs.OpenApiClient.Models.EmbedVariant.Full;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_text", n => { ActionText = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Action_Text>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Action_Text.CreateFromDiscriminatorValue); } },
                { "always_expanded", n => { AlwaysExpanded = n.GetBoolValue(); } },
                { "avatar", n => { Avatar = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input.WidgetConfig_Input_avatar>(global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input.WidgetConfig_Input_avatar.CreateFromDiscriminatorValue); } },
                { "bg_color", n => { BgColor = n.GetStringValue(); } },
                { "border_color", n => { BorderColor = n.GetStringValue(); } },
                { "border_radius", n => { BorderRadius = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Border_Radius>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Border_Radius.CreateFromDiscriminatorValue); } },
                { "btn_color", n => { BtnColor = n.GetStringValue(); } },
                { "btn_radius", n => { BtnRadius = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Btn_Radius>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Btn_Radius.CreateFromDiscriminatorValue); } },
                { "btn_text_color", n => { BtnTextColor = n.GetStringValue(); } },
                { "conversation_mode_toggle_enabled", n => { ConversationModeToggleEnabled = n.GetBoolValue(); } },
                { "custom_avatar_path", n => { CustomAvatarPath = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Custom_Avatar_Path>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Custom_Avatar_Path.CreateFromDiscriminatorValue); } },
                { "default_expanded", n => { DefaultExpanded = n.GetBoolValue(); } },
                { "disable_banner", n => { DisableBanner = n.GetBoolValue(); } },
                { "dismissible", n => { Dismissible = n.GetBoolValue(); } },
                { "end_call_text", n => { EndCallText = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.End_Call_Text>(global::Soenneker.ElevenLabs.OpenApiClient.Models.End_Call_Text.CreateFromDiscriminatorValue); } },
                { "end_feedback", n => { EndFeedback = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetEndFeedbackConfig>(global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetEndFeedbackConfig.CreateFromDiscriminatorValue); } },
                { "expand_text", n => { ExpandText = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Expand_Text>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Expand_Text.CreateFromDiscriminatorValue); } },
                { "expandable", n => { Expandable = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetExpandable>(); } },
                { "feedback_mode", n => { FeedbackMode = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetFeedbackMode>(); } },
                { "focus_color", n => { FocusColor = n.GetStringValue(); } },
                { "language_presets", n => { LanguagePresets = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input_language_presets>(global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input_language_presets.CreateFromDiscriminatorValue); } },
                { "language_selector", n => { LanguageSelector = n.GetBoolValue(); } },
                { "listening_text", n => { ListeningText = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Listening_Text>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Listening_Text.CreateFromDiscriminatorValue); } },
                { "markdown_link_allow_http", n => { MarkdownLinkAllowHttp = n.GetBoolValue(); } },
                { "markdown_link_allowed_hosts", n => { MarkdownLinkAllowedHosts = n.GetCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.AllowlistItem>(global::Soenneker.ElevenLabs.OpenApiClient.Models.AllowlistItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "markdown_link_include_www", n => { MarkdownLinkIncludeWww = n.GetBoolValue(); } },
                { "mic_muting_enabled", n => { MicMutingEnabled = n.GetBoolValue(); } },
                { "override_link", n => { OverrideLink = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Override_Link>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Override_Link.CreateFromDiscriminatorValue); } },
                { "placement", n => { Placement = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetPlacement>(); } },
                { "shareable_page_show_terms", n => { ShareablePageShowTerms = n.GetBoolValue(); } },
                { "shareable_page_text", n => { ShareablePageText = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Shareable_Page_Text>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Shareable_Page_Text.CreateFromDiscriminatorValue); } },
                { "show_agent_status", n => { ShowAgentStatus = n.GetBoolValue(); } },
                { "show_avatar_when_collapsed", n => { ShowAvatarWhenCollapsed = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Show_Avatar_When_Collapsed>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Show_Avatar_When_Collapsed.CreateFromDiscriminatorValue); } },
                { "show_conversation_id", n => { ShowConversationId = n.GetBoolValue(); } },
                { "speaking_text", n => { SpeakingText = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Speaking_Text>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Speaking_Text.CreateFromDiscriminatorValue); } },
                { "start_call_text", n => { StartCallText = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Start_Call_Text>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Start_Call_Text.CreateFromDiscriminatorValue); } },
                { "strip_audio_tags", n => { StripAudioTags = n.GetBoolValue(); } },
                { "styles", n => { Styles = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetStyles>(global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetStyles.CreateFromDiscriminatorValue); } },
                { "supports_text_only", n => { SupportsTextOnly = n.GetBoolValue(); } },
                { "syntax_highlight_theme", n => { SyntaxHighlightTheme = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Syntax_Highlight_Theme>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Syntax_Highlight_Theme.CreateFromDiscriminatorValue); } },
                { "terms_html", n => { TermsHtml = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Html>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Html.CreateFromDiscriminatorValue); } },
                { "terms_key", n => { TermsKey = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Key>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Key.CreateFromDiscriminatorValue); } },
                { "terms_text", n => { TermsText = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Text>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Text.CreateFromDiscriminatorValue); } },
                { "text_color", n => { TextColor = n.GetStringValue(); } },
                { "text_contents", n => { TextContents = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetTextContents>(global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetTextContents.CreateFromDiscriminatorValue); } },
                { "text_input_enabled", n => { TextInputEnabled = n.GetBoolValue(); } },
                { "transcript_enabled", n => { TranscriptEnabled = n.GetBoolValue(); } },
                { "variant", n => { Variant = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.EmbedVariant>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Action_Text>("action_text", ActionText);
            writer.WriteBoolValue("always_expanded", AlwaysExpanded);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input.WidgetConfig_Input_avatar>("avatar", Avatar);
            writer.WriteStringValue("bg_color", BgColor);
            writer.WriteStringValue("border_color", BorderColor);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Border_Radius>("border_radius", BorderRadius);
            writer.WriteStringValue("btn_color", BtnColor);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Btn_Radius>("btn_radius", BtnRadius);
            writer.WriteStringValue("btn_text_color", BtnTextColor);
            writer.WriteBoolValue("conversation_mode_toggle_enabled", ConversationModeToggleEnabled);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Custom_Avatar_Path>("custom_avatar_path", CustomAvatarPath);
            writer.WriteBoolValue("default_expanded", DefaultExpanded);
            writer.WriteBoolValue("disable_banner", DisableBanner);
            writer.WriteBoolValue("dismissible", Dismissible);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.End_Call_Text>("end_call_text", EndCallText);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetEndFeedbackConfig>("end_feedback", EndFeedback);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetExpandable>("expandable", Expandable);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Expand_Text>("expand_text", ExpandText);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetFeedbackMode>("feedback_mode", FeedbackMode);
            writer.WriteStringValue("focus_color", FocusColor);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input_language_presets>("language_presets", LanguagePresets);
            writer.WriteBoolValue("language_selector", LanguageSelector);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Listening_Text>("listening_text", ListeningText);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ElevenLabs.OpenApiClient.Models.AllowlistItem>("markdown_link_allowed_hosts", MarkdownLinkAllowedHosts);
            writer.WriteBoolValue("markdown_link_allow_http", MarkdownLinkAllowHttp);
            writer.WriteBoolValue("markdown_link_include_www", MarkdownLinkIncludeWww);
            writer.WriteBoolValue("mic_muting_enabled", MicMutingEnabled);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Override_Link>("override_link", OverrideLink);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetPlacement>("placement", Placement);
            writer.WriteBoolValue("shareable_page_show_terms", ShareablePageShowTerms);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Shareable_Page_Text>("shareable_page_text", ShareablePageText);
            writer.WriteBoolValue("show_agent_status", ShowAgentStatus);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Show_Avatar_When_Collapsed>("show_avatar_when_collapsed", ShowAvatarWhenCollapsed);
            writer.WriteBoolValue("show_conversation_id", ShowConversationId);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Speaking_Text>("speaking_text", SpeakingText);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Start_Call_Text>("start_call_text", StartCallText);
            writer.WriteBoolValue("strip_audio_tags", StripAudioTags);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetStyles>("styles", Styles);
            writer.WriteBoolValue("supports_text_only", SupportsTextOnly);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Syntax_Highlight_Theme>("syntax_highlight_theme", SyntaxHighlightTheme);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Html>("terms_html", TermsHtml);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Key>("terms_key", TermsKey);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Terms_Text>("terms_text", TermsText);
            writer.WriteStringValue("text_color", TextColor);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetTextContents>("text_contents", TextContents);
            writer.WriteBoolValue("text_input_enabled", TextInputEnabled);
            writer.WriteBoolValue("transcript_enabled", TranscriptEnabled);
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.EmbedVariant>("variant", Variant);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageAvatar"/>, <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.OrbAvatar"/>, <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.URLAvatar"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WidgetConfig_Input_avatar : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageAvatar"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageAvatar? ImageAvatar { get; set; }
#nullable restore
#else
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageAvatar ImageAvatar { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.OrbAvatar"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.OrbAvatar? OrbAvatar { get; set; }
#nullable restore
#else
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.OrbAvatar OrbAvatar { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.URLAvatar"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.URLAvatar? URLAvatar { get; set; }
#nullable restore
#else
            public global::Soenneker.ElevenLabs.OpenApiClient.Models.URLAvatar URLAvatar { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input.WidgetConfig_Input_avatar"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input.WidgetConfig_Input_avatar CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.ElevenLabs.OpenApiClient.Models.WidgetConfig_Input.WidgetConfig_Input_avatar();
                result.ImageAvatar = new global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageAvatar();
                result.OrbAvatar = new global::Soenneker.ElevenLabs.OpenApiClient.Models.OrbAvatar();
                result.URLAvatar = new global::Soenneker.ElevenLabs.OpenApiClient.Models.URLAvatar();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ImageAvatar != null || OrbAvatar != null || URLAvatar != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ImageAvatar, OrbAvatar, URLAvatar);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.ImageAvatar>(null, ImageAvatar, OrbAvatar, URLAvatar);
            }
        }
    }
}
#pragma warning restore CS0618
