// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkspaceWebhookResponseModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The auth_type property</summary>
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookAuthMethodType? AuthType { get; set; }
        /// <summary>Original creation time of the webhook.</summary>
        public int? CreatedAtUnix { get; set; }
        /// <summary>Whether the webhook has been automatically disabled due to repeated consecutive failures over a long period of time.</summary>
        public bool? IsAutoDisabled { get; set; }
        /// <summary>Whether the webhook has been manually disabled by a user.</summary>
        public bool? IsDisabled { get; set; }
        /// <summary>The most recent error code returned from the callback URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Error_Code? MostRecentFailureErrorCode { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Error_Code MostRecentFailureErrorCode { get; set; }
#endif
        /// <summary>The most recent time the webhook failed, failures are any non-200 codes returned by the callback URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Timestamp? MostRecentFailureTimestamp { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Timestamp MostRecentFailureTimestamp { get; set; }
#endif
        /// <summary>The display name for this webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The list of products that are currently configured to trigger this webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Usage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.ElevenLabs.OpenApiClient.Models.Usage Usage { get; set; }
#endif
        /// <summary>The unique ID for this webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookId { get; set; }
#nullable restore
#else
        public string WebhookId { get; set; }
#endif
        /// <summary>The HTTPS callback URL that is called when this webhook is triggered in the platform.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookUrl { get; set; }
#nullable restore
#else
        public string WebhookUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.WorkspaceWebhookResponseModel"/> and sets the default values.
        /// </summary>
        public WorkspaceWebhookResponseModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.WorkspaceWebhookResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ElevenLabs.OpenApiClient.Models.WorkspaceWebhookResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ElevenLabs.OpenApiClient.Models.WorkspaceWebhookResponseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auth_type", n => { AuthType = n.GetEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookAuthMethodType>(); } },
                { "created_at_unix", n => { CreatedAtUnix = n.GetIntValue(); } },
                { "is_auto_disabled", n => { IsAutoDisabled = n.GetBoolValue(); } },
                { "is_disabled", n => { IsDisabled = n.GetBoolValue(); } },
                { "most_recent_failure_error_code", n => { MostRecentFailureErrorCode = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Error_Code>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Error_Code.CreateFromDiscriminatorValue); } },
                { "most_recent_failure_timestamp", n => { MostRecentFailureTimestamp = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Timestamp>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Timestamp.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Usage>(global::Soenneker.ElevenLabs.OpenApiClient.Models.Usage.CreateFromDiscriminatorValue); } },
                { "webhook_id", n => { WebhookId = n.GetStringValue(); } },
                { "webhook_url", n => { WebhookUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.WebhookAuthMethodType>("auth_type", AuthType);
            writer.WriteIntValue("created_at_unix", CreatedAtUnix);
            writer.WriteBoolValue("is_auto_disabled", IsAutoDisabled);
            writer.WriteBoolValue("is_disabled", IsDisabled);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Error_Code>("most_recent_failure_error_code", MostRecentFailureErrorCode);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Most_Recent_Failure_Timestamp>("most_recent_failure_timestamp", MostRecentFailureTimestamp);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.ElevenLabs.OpenApiClient.Models.Usage>("usage", Usage);
            writer.WriteStringValue("webhook_id", WebhookId);
            writer.WriteStringValue("webhook_url", WebhookUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
