// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.ElevenLabs.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workspaces\api-keys\revoke
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RevokeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RevokeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/api-keys/revoke?api_key_name={api_key_name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RevokeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workspaces/api-keys/revoke?api_key_name={api_key_name}", rawUrl)
        {
        }
        /// <summary>
        /// Revoke the API key used to authenticate this request. Requires the query parameter `api_key_name=self` as an explicit confirmation.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeDeleteResponse?> DeleteAsync(Action<RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder.RevokeRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeDeleteResponse> DeleteAsync(Action<RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder.RevokeRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.ElevenLabs.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeDeleteResponse>(requestInfo, global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeDeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Revoke the API key used to authenticate this request. Requires the query parameter `api_key_name=self` as an explicit confirmation.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder.RevokeRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder.RevokeRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.ElevenLabs.OpenApiClient.V1.Workspaces.ApiKeys.Revoke.RevokeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Revoke the API key used to authenticate this request. Requires the query parameter `api_key_name=self` as an explicit confirmation.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RevokeRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Must be set to `self` to revoke the API key used to authenticate this request. Required as an explicit confirmation to avoid accidental revocation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api_key_name")]
            public string? ApiKeyName { get; set; }
#nullable restore
#else
            [QueryParameter("api_key_name")]
            public string ApiKeyName { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
