// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.ElevenLabs.OpenApiClient.V1.Dubbing.Item.Transcripts.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.V1.Dubbing.Item.Transcripts
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\dubbing\{dubbing_id}\transcripts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TranscriptsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.ElevenLabs.OpenApiClient.v1.dubbing.item.transcripts.item collection</summary>
        /// <param name="position">ISO-693 language code to retrieve the transcript for. Use &apos;source&apos; to fetch the transcript of the original media.</param>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Dubbing.Item.Transcripts.Item.WithLanguage_codeItemRequestBuilder"/></returns>
        public global::Soenneker.ElevenLabs.OpenApiClient.V1.Dubbing.Item.Transcripts.Item.WithLanguage_codeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("language_code", position);
                return new global::Soenneker.ElevenLabs.OpenApiClient.V1.Dubbing.Item.Transcripts.Item.WithLanguage_codeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Dubbing.Item.Transcripts.TranscriptsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TranscriptsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/dubbing/{dubbing_id}/transcripts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Dubbing.Item.Transcripts.TranscriptsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TranscriptsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/dubbing/{dubbing_id}/transcripts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
