// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.V1.SpeechToText
{
    /// <summary>The ID of the model to use for transcription.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BodySpeechToTextV1SpeechToTextPostPostRequestBody
    {
        [EnumMember(Value = "scribe_v1")]
        #pragma warning disable CS1591
        Scribe_v1,
        #pragma warning restore CS1591
        [EnumMember(Value = "scribe_v2")]
        #pragma warning disable CS1591
        Scribe_v2,
        #pragma warning restore CS1591
    }
}
