// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.ElevenLabs.OpenApiClient.Models;
using Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\convai\mcp-servers\{mcp_server_id}\tool-approvals
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ToolApprovalsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.ElevenLabs.OpenApiClient.v1.convai.mcpServers.item.toolApprovals.item collection</summary>
        /// <param name="position">Name of the MCP tool to remove approval for.</param>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.Item.WithTool_nameItemRequestBuilder"/></returns>
        public global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.Item.WithTool_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tool_name", position);
                return new global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.Item.WithTool_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.ToolApprovalsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToolApprovalsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/convai/mcp-servers/{mcp_server_id}/tool-approvals", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.ToolApprovalsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToolApprovalsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/convai/mcp-servers/{mcp_server_id}/tool-approvals", rawUrl)
        {
        }
        /// <summary>
        /// Add approval for a specific MCP tool when using per-tool approval mode.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPServerResponseModel"/></returns>
        /// <param name="body">Request model for adding approval for a single MCP tool.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ElevenLabs.OpenApiClient.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPServerResponseModel?> PostAsync(global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPToolAddApprovalRequestModel body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPServerResponseModel> PostAsync(global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPToolAddApprovalRequestModel body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.ElevenLabs.OpenApiClient.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPServerResponseModel>(requestInfo, global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPServerResponseModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add approval for a specific MCP tool when using per-tool approval mode.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request model for adding approval for a single MCP tool.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPToolAddApprovalRequestModel body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.ElevenLabs.OpenApiClient.Models.MCPToolAddApprovalRequestModel body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.ToolApprovalsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.ToolApprovalsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.ElevenLabs.OpenApiClient.V1.Convai.McpServers.Item.ToolApprovals.ToolApprovalsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ToolApprovalsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
